spring:
  jpa:
    show-sql: false
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

fastapi:
  url: ${FAST_API_URL}

server:
  tomcat:
    threads:
      max: 100
      min-spare: 10

logging:
  request:
    enabled: false

app:
  version:
      minVersion: 1.1.0
      latestVersion: 1.2.0